conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: diffusercam
  root: ./data/diffuser_cam/

measurement:
  operator:
    name: convolution

  noise: 
    name: gaussian
    sigma: 0.05
